name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MY_ENV  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "key_name=${{ secrets.KEY_NAME }}"
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Get EC2 Public IP
        id: tf
        run: echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Update Ansible Inventory
        run: |
          sed -i "s/EC2_PUBLIC_IP/${{ steps.tf.outputs.IP }}/" ansible/inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml  

      
